### ISSUE TITLE
Can't specify multiple ciphers in fstab

### ISSUE THREAD

**Issue by Harvie** [libfuse/sshfs#104]
Hello, i'd like to set multiple ciphers, eg.: aes128-gcm@openssh.com,arcfour128,blowfish-cbc

But it does not really make sense in fstab, since commas are already used to separate mount options:
```
defaults,user,ro,allow_other,reconnect,delay_connect,cipher=aes128-gcm@openssh.com,arcfour128,blowfish-cbc,ConnectTimeout=5,ServerAliveInterval=5
```
Can you please add some other character that would translate to comma before calling ssh? eg. pipe:

```
defaults,user,ro,allow_other,reconnect,delay_connect,cipher=aes128-gcm@openssh.com|arcfour128|blowfish-cbc,ConnectTimeout=5,ServerAliveInterval=5
```

**Comment by Nikratio** [comment]
I don't think that's worth adding. I'd suggest to simply add those options in a configuration file (and add support for specifying that in fstab). 

Would you be interested in working on this? If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by knutov** [comment]
I have the same question. 

My scenario is to have fallback cipher - so it will be possible to use one string for all connection and it will work with older and newer openssh for example. And the speed will be automatically faster after upgrading openssh from 5.3 to 6.8 as a bonus.

**Comment by Nikratio** [comment]
Closing per my previous message.
