### ISSUE TITLE
Feature request: hide hidden files

### ISSUE THREAD

**Issue by sganis** [libfuse/sshfs#140]
Is there a feature to hide hidden files? I am using sshfs cygwin to mount a remote linux storage, and I need to hide files that start with a dot. If not, any suggestion of what function to modify would be helpful. Thanks.

**Comment by Nikratio** [comment]
Thanks for the idea! Unfortunately, there is no such thing as a "hidden file" as far as FUSE is concerned. Therefore, sshfs can't provide anything like it.

**Comment by Nikratio** [comment]
Interesting idea. That would lead to other weird behavior though, like not being able to delete an apparently empty directory (because it contains files that sshfs hides).

**Comment by sganis** [comment]
True, but it shouldn’t be a big issue. Deleting a folder means deleting folder and content these days, as it is in windows, and I have never used rmdir in linux, I always use rm -r. 
Another reason for this feature, almost all mounting technologies in windows have some option to hide hidden linux files. 
Yet another, many tools in linux have this option by default, such as /bin/ls.

**Comment by Nikratio** [comment]
That's actually exactly the problem :-). If you execute `rm -r`, then the `rm` commands asks the filesystem for a list of files, deletes each of them, and then attempts to delete the directory. Windows Explorer does the same thing. This will fail if the file system hides certain files, because it cannot know whether it's asked for a list of files to be displayed to the user, or a list of files to be removed by a recursive removal operation.

**Comment by sganis** [comment]
The filesystem could know about hidden files, only the sshfs readdir operacion could filter them, what do you think?
