### ISSUE TITLE
sshfs 2.x not working when controlled by pexpect

### ISSUE THREAD

**Issue by erjoalgo** [libfuse/sshfs#142]
When I run the sshfs command from within a pexpect-controlled process and without the debug flag (`-d`), although the process exits with status 0, the share is not mounted.
 
With the debug flag mounting works as expected, but in the foreground, and umounts after exit.

Other users have reported this problem:

https://serverfault.com/questions/117776/sshfs-is-not-working

**Comment by erjoalgo** [comment]
$sshfs --version
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
SSHFS version 2.8

**Comment by Nikratio** [comment]
Thanks for the report! Is this still a problem with the newest SSHFS version (3.x)? I'm afraid this will probably not be fixed in 2.x unless someone else volunteers to do the work. 

If the problem still exists in 3.x: what happens if you specify `-f` instead of `-d`? What is the output (presumably read by pexpect, but there should be a way to see what pexpect sees) when the mount does not  come up?

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!

**Comment by erjoalgo** [comment]
Thanks. It appears that the issue may have been related to the parent process exiting without detaching the child.
