### ISSUE TITLE
Feature request: add option to redirect stderr to a file

### ISSUE THREAD

**Issue by carl-mastrangelo** [libfuse/sshfs#152]
When sshfs is not run in the foreground, it appears that stderr is redirected to /dev/null.  It would be nice if there was an option to forward this to a file, to make it easier to debug.

**Comment by carl-mastrangelo** [comment]
@Nikratio 

The main thing to me was discoverability (i.e. making a command line option makes the user aware that its possible).  It wasn't obvious from the `--help` page where stdout went, or that it was related to being in the background or foreground.  After looking through the source code, I event found where ssh's output was redirected, but it would have been easier if I didn't have to.

Another alternative is to call out where the pipes are connected in the man page.  That would have given me the breadcrumb I needed to find out that it was foreground that I actually wanted.

Thoughts?

**Comment by Nikratio** [comment]
It's not mentioned anywhere in the SSHFS docs because it's a Unix default. If one process starts another, it gets the same stdin/stdout :-).

Happy to add it to the manpage though if you want to create a pull request.

**Comment by Nikratio** [comment]
I'm closing this issue for now. This isn't meant to be a rejection of the idea itself, it's just that there is little point in keeping enhancement/wishlist requests in the bug tracker that no-one intends to work on. (I want to use the tracker as a tool to manage ongoing work rather than a database of possible enhancements).
