### ISSUE TITLE
ssh only mode

### ISSUE THREAD

**Issue by tecan** [libfuse/sshfs#154]
use rsync,scp or uuencode options and ls, move , cp to browse files, no need for sftp.

**Comment by Nikratio** [comment]
Thanks for the report! This sounds like a great idea for a new project, because it really doesn't have anything to do with sshfs in its form :-).

**Comment by bersbersbers** [comment]
That's a bummer! I found this issue because sshfs stopped working for me while MobaXterm and WinSCP continued working. (Something bad happens when requesting the `sftp` subsystem - it's probably my admin getting more restrictive again.) It turns out the other two have transparent fallback to SCP, so I though this must be easy. Apparently, it's not ;)

**Comment by netpipe** [comment]
i might have a solution for this https://github.com/netpipe/QPiper

**Comment by bersbersbers** [comment]
@netpipe thanks - would you mind explaining what this project does and how I can use it to solve this issue? Project document is pretty sparse ;)
