### ISSUE TITLE
Add inotify support

### ISSUE THREAD

**Issue by ChristianMayer** [libfuse/sshfs#155]
It would be great when inotify would work on files mounted through sshfs.

Note: this might require the addition of an custom extension to sftp which would need to be implemented in OpenSSH first to be able to add the support in sshfs.

**Comment by Nikratio** [comment]
This is a great idea, thanks for taking the time to suggest it! Do you think you could work on this (or do you know someone who could)?

sshfs is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary
work. Suggestions for new features that are just submitted to the issue tracker are therefore unlikely to result in the feature being implemented - as great as the feature might be. 

So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

(note that for this to happen, you'd also first need to add inotify support to libfuse, so this is quite an extensive project)

**Comment by ChristianMayer** [comment]
As I'm too busy with my own OSS projects I have no spare time to help out here.
Actually working on my project in the IntelliJ IDEA I stumbled over this issue as the IDE needs to keep track of external changes.

I created this issue as others seem to have the same problem (cf. https://unix.stackexchange.com/questions/144486/how-do-i-use-inotify-or-named-pipes-over-sshfs ) and it wasn't documented here as a feature request.
