### ISSUE TITLE
SSHFS doesn't survive loss of connectivity

### ISSUE THREAD

**Issue by jaredpz** [libfuse/sshfs#159]
Hi all,

I want to mount a drive using sshfs on a server that I use a VPN to connect to. I have no problem mounting the drive when I'm connected to the VPN, but once I'm off the network the server is no longer available and the drive becomes inaccessible. After I've disconnected if I try to `ls` the directory where I put the mount it just says "ls .: device not configured" and the mounted drive disappears from Finder (I still see the folder I mounted it to in Terminal, but not Finder). To get it to work again I have to reconnect to VPN, unmount the location I mounted the drive previously and remount. Is there a way to get it so that the drive automatically reconnects and remounts when I log back into my VPN? If I have to remount every time I might as well just us sftp to connect to the drive when I need to, but having a mounting solution would be much preferable.

I'm on OSX 10.14.3 and the command I used to mount the drive was:
```sshfs user@server.address:/source/dir/here ~/local_mount -o auto_cache,reconnect,defer_permissions,noappledouble,volname=Local_Name```

Thanks!

**Comment by Nikratio** [comment]
This should work. For SSHFS, disconnecting for the VPN isn't any different than disconnecting from the network entirely. It should retry periodically and the mountpoint should eventually become accessible again.

The error message indicates that SSHFS is crashing instead - could you confirm that the process is no longer runnig? And maybe run SSHFS in foreground under a debugger to determine what exactly is going on?

(Note that the chances of this being fixed in SSHFS 2.x are very slim though, this version isn't supported anymore).

**Comment by Nikratio** [comment]
I'm closing this bug report for now. Please note that this isn't meant to imply that you haven't found a bug - you most likely have and I'm grateful that you took the time to report it. However, without additional information it is unlikely that anyone is going to be able to do anything but this, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues). 

Please feel free to re-open this if you can provide the requested information!
