### ISSUE TITLE
dot in mount point's directory name -> not mounting

### ISSUE THREAD

**Issue by koem** [libfuse/sshfs#163]
Hi,

I tried to mount to a directory with a dot in it's name. Result was no error message and the directory didn't contain anything. `mount` didn't show it, too.

`sshfs -p 48574 me@raspi.lalala.net:/media/Backup2_Me/ /media/Backup2.enc/ -o idmap=user -o uid=0 -o gid=0 `

remote and local: Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
`root@raspberrypi:~ # sshfs -V`
`SSHFS version 2.8`
`FUSE library version: 2.9.7`
`fusermount version: 2.9.7`
`using FUSE kernel interface version 7.19`

When I mounted to /mnt everything worked as expected...

**Comment by Nikratio** [comment]
Thanks for the report! For me this works just fine:

```
$ md test.dot
$ sshfs ebox:/tmp test.dot
$ dir test.dot/
total 4.0K
drwx------ 1 root root 4.0K Apr  4 07:05 systemd-private-e8caeaa9857049e9a17db0fc14d83d25-apache2.service-SDGndy
$ fusermount -u test.dot
$ sshfs --version
SSHFS version 2.8
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

Could you please give me detailed instructions for reproducing this? And try to update to the newest SSHFS version?

**Comment by koem** [comment]
Well, actually that's all I can provide. I ran the mount command as root.

**Comment by rsyncnet** [comment]
We (rsync.net) cannot reproduce this error - it is interesting for us because the daily/weekly/monthly snapshots in customer accounts reside in the:

.zfs/snapshot

directory.  So I checked with:

sshfs 1005@usw-s002.rsync.net:.zfs /mnt/zfs  (blah blah other options)

... and it mounted correctly and I was able to browse the .zfs/snapshot directory on the remote host.
