### ISSUE TITLE
Monitoring SSHFS mount point with SNMP in Ubuntu

### ISSUE THREAD

**Issue by miladjahandideh** [libfuse/sshfs#177]
We want to monitor SSHFS mount point with SNMP in Ubuntu but it doesn't show any SSHFS mount point. Maybe because it is encrypted. Is it possible?

`snmpwalk -v 2c -c public localhost UCD-SNMP-MIB::dskTable 
`or

`snmpwalk -v 2c -c public localhost HOST-RESOURCES-MIB::hrFSRemoteMountPoint
`

When we request with above commands there is no mountpoint in the result but we have MountPoint when we do df.

`df `

**Comment by Nikratio** [comment]
Thanks for your interest in SSHFS! As far as I can tell, this is a question about how to use SSHFS rather than a bug report. Could you please send your question to the SSHFS mailing list  https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
