### ISSUE TITLE
OpenVMS Versioning File System - zero length file

### ISSUE THREAD

**Issue by Ca-Al** [libfuse/sshfs#191]
I found an issue on the sourceforge website that matches my issue exactly
https://sourceforge.net/p/fuse/mailman/message/30813677/
but there's no follow up response.
Essentially OpenVMS uses a versioning file system which I am mounting on Linux using sshfs. It works great for reads, and the initial write that creates the file, but subsequent creation writes behave in an unexpected manner. 
The initial write creates the file, say TEST.TXT;1 with the expected content ( ; is used to denote version in OpenVMS). A 2nd write/creation of TEST.TXT then overwrites the content of TEST.TXT;1 with the content intended for the 2nd version of the file and also creates a zero length file TEST.TXT;2 . A 3rd write to a new TEST.TXT places the content of the 3rd write into TEST.TXT;2 and creates a new zero lenth file TEST.TXT;3 . 

I have tried using various mount options such as workaround=norename, use_ino, allow_other, no_writeback_cache, direct_io, no_async_dio in the hope that I may stumble upon something that works for me, but nothing has so far.

I understand that OpenVMS is probably seen as a defunct system and it is unlikely that anyone would want to spend time writing code to support it, but if you can share of any combination of options that may possibly work for me I would appreciate it.

I'm happy to provide a simple test case and debug output if that would help.

**Comment by Nikratio** [comment]
Thanks for your interest in SSHFS! As far as I can tell, this is a question about how to use SSHFS rather than a bug report (or possibly a bug in OpenVMS's SSH implementation). 

Could you please send your question to the SSHFS mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
