### ISSUE TITLE
sshfs don't return personnal ssh banner, fingerprint or visualhostkey

### ISSUE THREAD

**Issue by jeg139** [libfuse/sshfs#195]
Hi,
sshfs only return fingerprint and visualhostkey if the host is unknown. After you accept the host key, he don't return the fingerprint and visualhostkey anymore and never show the banner message or personnal banner message. is it possible to make it show no-error message from ssh?
I'm looking at the code, but it's my first day looking at. Maybe someone can make a patch faster than me.
Thanks for reading, and I help if I can.

**Comment by jeg139** [comment]
Sorry if the fix already exist. I just see the debian 10 buster stable version is highly outdated.
version : 2.10+repack-2.
You can close the issue if the fix already exist.

**Comment by Nikratio** [comment]
Thanks for the report! Do you think you could work on this (or do you know someone who could)?

SSHFS is a fully volunteer driven project. This means that new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches. If not, I will close this issue in a few days (since the purpose of the issue tracker is to coordinate ongoing and planned work, rather than enumerate all the work that could possibly be done).

**Comment by jeg139** [comment]
Thanks for your reply,
I can't because i don't have the knowledge. I think you can close the issue and if i find someone of course i will tell him to work on that. It could be a good feature.

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a valid bug or potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors or developers. The current maintainer continues to apply pull requests and tries to make regular releases, but unfortunately has no capacity to do any development beyond addressing high-impact issues. Any other reports are therefore likely to languish unless they come together with a high-quality pull request.

This report unfortunately does not fall into either category, so with the current state of affairs it's unlikely that anyone is going to be able to do anything but this anytime soon, and I prefer to use the issue tracker as a tool to manage ongoing work (as opposed to a database of known/potential issues).
