### ISSUE TITLE
broken sqlite db on concurrent access

### ISSUE THREAD

**Issue by bam80** [libfuse/sshfs#204]
Hello, I got sshfs mounted sqlite db corruption when accessing concurrently with remote and local clients.
Does sshfs supports locking?
Anything I could try?

**Comment by Nikratio** [comment]
Thanks for your interest in SSHFS! As far as I can tell, this is a question about how to use SSHFS rather than a bug report. Could you please send your question to the SSHFS mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!

**Comment by grahamperrin** [comment]
I have a comparable question about concurrent writes. Is https://sourceforge.net/p/fuse/mailman/message/36048718/ (2017) a good starting point? I'm not a developer; it's quite difficult for me to understand.
