### ISSUE TITLE
small Question: recommended way of getting current stable version of sshfs to Ubuntu

### ISSUE THREAD

**Issue by alexanderadam** [libfuse/sshfs#208]
First of all: thank you so much for maintaining sshfs! :pray: 

I recently [ran into an issue that left my photos destroyed](https://stackoverflow.com/questions/60434201/how-to-repair-jpegs-like-okular-sees-them) and now I obviously don't want to have this repeated.

I'm using Ubuntu 18.04.4 LTS which seems to have sshfs 2.8 and I don't found any open issue that was focussing on backporting the bugfix to the Ubuntu 18.04 version.
Now I'm obviously curious which way is the preferred variant of getting a bugfixed version to Ubuntu 18.07. I didn't find any PPA. Would you recommend installing the binary [from GitHub releases](https://github.com/libfuse/sshfs/releases)? Then I won't get any other patches automatically I guess? Or is there any other recommendation?

**Comment by Nikratio** [comment]
Thanks for your interest in SSHFS! As far as I can tell, this is a question about how to use SSHFS rather than a bug report. Could you please send your question to the SSHFS mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!

As for your question: I'd recommend to use the Debian package - you may have to recompile it from source though.
