### ISSUE TITLE
Clarifying multi-user simultaneous writing

### ISSUE THREAD

**Issue by jwatt** [libfuse/sshfs#209]
On https://en.wikipedia.org/wiki/SSHFS it says:

```
SSHFS is an alternative to those protocols only in
situations where users are confident that files and
directories will not be targeted for writing by
another user, at the same time
```

That seems alarming. If that's true it would seem to be prudent to have a LIMITATIONS or WARNING section in the readme. If not, I guess that section of the Wikipedia page should be removed, or that understanding clarified as being wrong. Can someone clarify?

**Comment by Nikratio** [comment]
Thanks for your interest in SSHFS! As far as I can tell, this is a question about how to use SSHFS rather than a bug report. Could you please send your question to the SSHFS mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
