### ISSUE TITLE
authentification using phrase-less shh keys and server password

### ISSUE THREAD

**Issue by peterthorpe5** [libfuse/sshfs#215]
Dear lovely people,

This is not a bug as such but a plea for help. Would someone please be able to tell me how to make sshfs connect to a server which requires passphrase-less ssh keys and a server password?

Shhfs did previously successfully connect to this server, until the security requirements changed, which now a passphrase-less ssh key as well.

Moreover, is there any specific configuration on the server side which is required to allow this to happen, for example in the ssh_conf?

Regards, 

Pete

**Comment by Nikratio** [comment]
Thanks for your interest in SSHFS! As far as I can tell, this is a question about how to use SSHFS rather than a bug report. Could you please send your question to the SSHFS mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
