### ISSUE TITLE
Cannot delete file in share that has recycle bin

### ISSUE THREAD

**Issue by antegs** [libfuse/sshfs#218]
Connecting to a Synology share with the latest sshfs and debug enabled.  When the share has no recycle bin enabled, all file operations run with no problem, including deletions.

Creation and deletion of a file:
https://pastebin.com/mvQB97yk
Log file of above transaction:
https://pastebin.com/Yrqra9LY

But when Recycle Bin is enabled on the Synology share, access and creation of files is still OK but deletion gives "Permission denied".

Creation and attempted deletion of a file:
https://pastebin.com/2UkAme88
Log file of above transaction:
https://pastebin.com/AkBZ0HWj

Similar creation and deletion using an SMB connection has no problems.  I have tried all kinds of options with sshfs, including cache disabling and workarounds, without success.

**Comment by Nikratio** [comment]
Thanks for your interest in SSHFS! As far as I can tell, this is a question about how to use SSHFS rather than a bug report. Could you please send your question to the SSHFS mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
