### ISSUE TITLE
ProxyJump stopped working

### ISSUE THREAD

**Issue by 2sn** [libfuse/sshfs#219]
I noticed that since within the last few weeks the 'ProxyJump" option in `.ssh/config` stopped working.  It used to work seamlessly before.

Example `.ssh/config file`

```
Host A
Hostname myproxy.org
User myself

Host B
Hostname myremote.org
User myself
ProxyJump A
```
if I now use `sshfs B:remote local`

it no longer works; I tried for a case where no proxy was needed, and adding the proxy prevented connection.  I can log in using the same configuration.  It got stuck after the line (in 'LogLevel DEBUG3')
```
debug1: Local version string SSH-2.0-OpenSSH_8.3
```

Other info:
```
Fedora 32, Kernel 5.7.7, on all machines involved.
SSHFS version 3.7.0
FUSE library version 3.9.1
using FUSE kernel interface version 7.31
fusermount3 version: 3.9.1
```

**Comment by Nikratio** [comment]
Thanks for your interest in SSHFS! As far as I can tell, this is a question about how to use SSHFS rather than a bug report. Could you please send your question to the SSHFS mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
