### ISSUE TITLE
SSHFS reconnect

### ISSUE THREAD

**Issue by Beechnut1** [libfuse/sshfs#228]
Good Day All,

      SSHFS has worked for me well, but I'm having an issue with it disconnecting.  I'm looking for the best way to have it reconnect itself when it disconnects.  I'm a little bit of a novice at this but I've learned a ton over the last few weeks.  I mount the drive in this way:
sshfs -o allow_other user@xxx.xxx.x.x/path/to  /path/to 

I've just tried to add this at the end to see if it worked, it did not:
sshfs -o allow_other user@xxx.xxx.x.x/path/to  /path/to -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3

Looking for suggestions on this. Do I need to add a command line to fstab? Or do I need to use keys?  Thanks in advance

**Comment by Nikratio** [comment]
Thanks for your interest in SSHFS! As far as I can tell, this is a question about how to use SSHFS rather than a bug report. Could you please send your question to the SSHFS mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!
