### ISSUE TITLE
Need ssh KeyAlgorithms support

### ISSUE THREAD

**Issue by bfree-github** [libfuse/sshfs#246]
In order to connect to servers via KeyAlgorithms, we need to be able to pass through the following ssh arguments:

-o KexAlgorithms
-o HostKeyAlgorithms

Is there a way for sshfs to pass arguments to ssh, or otherwise support KexAlgorithms?

**Comment by Nikratio** [comment]
Thanks for your interest in SSHFS! As far as I can tell, this is a question about how to use SSHFS rather than a bug report. Could you please send your question to the SSHFS mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!

**Comment by bfree-github** [comment]
Thanks for responding!  I had originally sent this to fuse-sshfs and they redirected me to lib-fuse, saying it wasn’t their issue.

Just to be clear, this is not about how to use sshfs, but rather adding a means in lib-fuse to pass in arbitrary ssh arguments, or specifically KexAuthority arguments.  Without this, sshfs can’t address the problem.

Thanks - Bob
