### ISSUE TITLE
Mac brew install failure

### ISSUE THREAD

**Issue by denningsrogue** [libfuse/sshfs#247]
Brew install sshfs results in the following error message:

sshfs has been disabled because it requires FUSE!

I have the latest version of MacFUSE  installed and am running the latest version of MacOS.

**Comment by rgm3** [comment]
Since macfuse is now closed-source, homebrew cannot include sshfs as a formula (although as a cask could work I believe).  I was unable to figure out how to get sshfs 3.7.1 to compile with macfuse 4.1.0, since this doesn't provide the libfuse3 dependency.  Homebrew's libfuse version 3.1.0 is linux-only. Unfortunately I believe macOS users are stuck with sshfs version 2.x, linked against fuse library 2.9.9.

For more info, refer to: https://github.com/Homebrew/brew/issues/9401 .

**Comment by Nikratio** [comment]
Closing this issues, since it's a problem with MacOS' FUSE support rather than SSHFS.
