### ISSUE TITLE
SSHFS freezes completely on a regular basis and requires reboots

### ISSUE THREAD

**Issue by freebrowser1** [libfuse/sshfs#254]
When using sshfs it sometimes cannot be stopped and cannot be killed even as root.
Some apps are locked up such as the Atom text editor accessing files on the remote server and a file browser accessing files on the same remote server.
I tried several options, see here:

https://askubuntu.com/questions/791002/how-to-prevent-sshfs-mount-freeze-after-changing-connection-after-suspend

but to no avail.
The target is a Linux Centos 7 Virtual Box session, so network issues should not be the problem, as I can normally ssh into this session.

A command like `sudo umount -f <sshfs mount point>` locks up as well.
Even `sudo reboot` or clicking on (apple icon) => Restart does not respond. It looks like malicious software. 

So I have to reboot my Mac by pressing the power button and everything works normally as long as sshfs is not running.

It happens with SSHFS 2.1.0 (which I can't upgrade to 3.71 via Homebrew which is another issue) and the installed 2.5.0.

**Comment by Nikratio** [comment]
Thanks for the report! Do you think you could work on this (or do you know someone who could)?

SSHFS is fully volunteer driven. This means new features and bugfixes are implemented only when someone has a personal interest in them and therefore also does the necessary work. So if someone (that probably means you) is interested in working on this, then I'd be happy to give guidance and review patches.

Note that SSHFS 2.5 is very, very old. So unless you take action on this, I don't think it's likely that anyone will take action on this bug.

**Comment by freebrowser1** [comment]
"Note that SSHFS 2.5 is very, very old."
True. But I don't have access to a newer version, and cannot build 3.7.1.
I'd be interested in working on this, but then I should be able to build sshfs.

**Comment by Nikratio** [comment]
I'm closing this issue for now. Please note that this isn't meant to imply that you haven't found a real bug or worthwhile potential improvement - you most likely have and I'm grateful that you took the time to report it.

Unfortunately, this project does not currently have any active, regular contributors. As the maintainer, I try to review pull requests and make regular releases, but unfortunately I have no capacity to do significant development beyond that.
Issue reports that do not come with a pull request or clearly have high impact on a large number of users are therefore likely to languish.

I understand that this is frustrating for users, but I hope you can also understand that any development work that I do on this project has to compete with spending time with my family, doing work that I get paid for, doing something recreational without a computer, or working on features/bugs that affect me personally. Most bugs and ideas - unfortunately including this one - loose out in this competition.

In other words, unless you plan to work on this yourself or can recruit someone who will, it's unlikely that anyone is going to do anything about it anytime soon.

Still, you may wonder why I am closing the issue rather than keeping it open.

In short, I want the issue tracker to show the most important issues that users should be aware of and where prospective contributors could make the biggest difference. I do not think there is much value in using it as an exhaustive database of every idea or glitch that someone has ever encountered - especially if no one is intending to address/implement it.

For this reason, I am closing most issues when it becomes clear that they're unlikely to see any activity in the near future - and this seems to be the case here.

I understand that you have invested time and effort in reporting this, and I am very sorry that currently there is no way to build upon this. I wish the situation was different.
