### ISSUE TITLE
Allow idmap'ping of numeric IDs

### ISSUE THREAD

**Issue by sebunger** [libfuse/sshfs#256]
Hi, I have a use-case where I need to make a remote tree available locally but with IDs mapped from the remote UIDs to a set of UIDs different from the local system. These belong to a chroot, but I cannot run sshfs inside the chroot since it is not installed there.

As far as I understand it, SSHFS maps numeric IDs received from the remote system to user names via the idmap=file,uidfile=remote-passwd options. It then looks the resulting name up in the local user-id store (similar to what getent does) and finally returns the resulting numeric ID to the local programs using fuse.

What I need is an option to replace the second lookup in the local user-id store with another lookup in a separate file. Something like
idmap=file,uidfile=remote-passwd,luidfile=chroot-passwd

All of this of course applies to group as well.

Is something like that achievable?
Alternatively, is it possible to pass a file to uidfile that allows a format of
local-id:remote-id
I.e. only look the name up in the local store if it isn't a valid integer.

**Comment by Nikratio** [comment]
Thanks for your interest in SSHFS! As far as I can tell, this is a question about how to use SSHFS rather than a bug report. Could you please send your question to the SSHFS mailing list (https://lists.sourceforge.net/lists/listinfo/fuse-sshfs), instead of using the issue tracker? I'd like to reserve use of the latter to actually track issues and not use it for discussion.

Thanks!

**Comment by sebunger** [comment]
Ah, it really is neither. It was a feature request, since, as far as I can tell, SSHFS cannot currently do what I wanted. Let me clarify what I need and if you then still believe that SSHFS is already capable of doing this, then I shall re-read the manuals and failing that contact the list you mentioned.

What I need is a way for SSHFS to map remote **numeric** user IDs to local **numeric** user IDs without referencing either the remote or local user database (e.g. /etc/passwd).

**Comment by Nikratio** [comment]
In principle SSHFS could do this, but I don't think it should. I'd encourage you to try to solve the problem differently - maybe look into user namespaces?

**Comment by sebunger** [comment]
I can't see how user namespaces would help here. I need to map UIDs from one space to another. It just so happens that the space is not that of the host SSHFS is running on. But it insists on using the hosts passwd DB to try to map names.

What I am asking for is actually a generalisation of the current mapping concept (simply allow the user to specify an alternative DB for the local passwd DB, just as it is already possible to specify an alternative for the remote DB).

May I ask why you think SSHFS **should** not do this? It seems the logical place to solve this.

**Comment by Nikratio** [comment]
I believe a user namespace is a mapping from one arbitrary set of UIDs to the host UIDs. I think this is exactly the problem you want to solve ("I need to map UIDs from one space to another").

I would therefore not attempt to have sshfs do any mapping and instead use a user namespace where the guest namespace corresponds to the remote host.

I do not think this functionality should be in SSHFS because SSHFS messing with usernames and password lookups is a buffer overflow waiting to happen and it's the wrong layer to solve the problem (e.g. scp would need to reimplement this if it's implemented only in SSHFS).

That said, the discussion is a bit moot because even if I was convinced this was a good idea I wouldn't have the time to implement it. SSHFS currently doesn't have any active developers.

**Comment by sebunger** [comment]
... "one arbitrary set of UIDs to the host UIDs". Exactly and I want to map from the space of the remote host to an arbitrary space that is NOT the local host.

**Comment by sebunger** [comment]
... "messing with usernames and password lookups" ... that's what it is doing now. I want it to not do that.

**Comment by sebunger** [comment]
Or else I'm completely missing how the mapping is currently working. I **believe** (correct me if I'm wrong) this is how SSH currently works:

- On the remote host, SSHD runs (no SSHFS code at all) which reports files with their numeric UID to the local host.
- On the local host SSHFS uses that remote numeric ID and translates it into a user name using the mapping file from the command line.
- Then it takes that user name and looks it up in the local host's user database to get back to a numeric UID
- That's UID that is reported to the local host kernel and eventually user-land programs via fuse.

What I would like is to replace the lookup in the local host's user database with a lookup in another given mapping file. Or, alternatively, to allow the given file to be a direct numeric UID to numeric UID mapping.
