### ISSUE TITLE
sshfs client memory consumption

### ISSUE THREAD

**Issue by Ric57100** [libfuse/sshfs#297]
Hi,

I would like to know why sshfs client consumes more and more memory over time, until it causes an out of memory (The remote FS contains a lot of small files). As you can see in the screenshot, after less than a month, the process uses almost 1GB of memory (RSS field), or even more than a GB taking into account the virtual memory (VSZ field).

To prevent such a situation I have to unmount / mount remote FS.
![image](https://github.com/libfuse/sshfs/assets/69900128/11bce533-850a-42a7-80e5-55156bf7958e)

Does anyone have an explanation?

**Comment by h4sh5** [comment]
It's because SSHFS caches file reads for improved performance. That probably means the more files you list / read, the more it stores in the cache in memory.

You should be able to disable that by using `-o cache=no`

(the option in help being `-o cache=BOOL          enable caching {yes,no} (default: yes)`)

**Comment by faridfarid912** [comment]
https://github.com/libfuse/sshfs/issues/297#issuecomment-2002369276
