### ISSUE TITLE
Append to file broken

### ISSUE THREAD

**Issue by hsandmeyer** [libfuse/sshfs#72]
I can not append to files any more. In the mounted directory:

```
$ echo foo > test.txt
$ echo bar >> test.txt
$ cat test.txt
bar
```
Same happens using other programs than the shell

System is arch-linux with newest updates.

```
sshfs --version

SSHFS version 3.0.0
FUSE library version 3.1.0
using FUSE kernel interface version 7.26
fusermount3 version: 3.1.0
```

**Comment by myagues** [comment]
Try disabling writeback_cache with `-o writeback_cache=no`.

**Comment by hsandmeyer** [comment]
Thank you. That helps

**Comment by Nikratio** [comment]
Thanks for the report! I will look into it ASAP.

**Comment by Nikratio** [comment]
A very similar problem with append operations is actually present in the `passthrough_fh` example that comes with libfuse itself. If writeback cache is enabled, we get:

```
$ echo foo > test.txt
$ echo bar >> test.txt
bash: echo: write error: Bad file descriptor
$ cat test.txt 
foo

```

**Comment by Nikratio** [comment]
Alright, so the problem is that SSHFS opens the file write-only, but writeback cache requires the ability to read the file. Opening read-write fixes the problem.

But the important question is: why aren't we getting an error from the remote server when trying to read from a write-only file? This is what's responsible for getting silent data corruptions instead of an error on the second write.

**Comment by Nikratio** [comment]
Reported the issue to the openssh folks. Should soon show up on https://marc.info/?l=openssh-unix-dev&r=1&b=201708&w=2.
